### ISSUE TITLE
Deprecation warning for Tapable.plugin 

### ISSUE THREAD

**Issue by gparonitti** [hxlniada/webpack-concat-plugin#58]
Hi there,

How can I get rid of the following deprecation warning that it seems spawn from your plugin?

```
(node:10584) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at /[MY/PATH]/node_modules/webpack-concat-plugin/release.js:150:42
    at new Promise (<anonymous>)
    at ConcatPlugin.resolveReadFiles (/[MY/PATH]/node_modules/webpack-concat-plugin/release.js:149:49)
    at ConcatPlugin.apply (/[MY/PATH]/node_modules/webpack-concat-plugin/release.js:287:18)
    at webpack (/[MY/PATH]/node_modules/webpack/lib/webpack.js:37:12)
    at processOptions (/[MY/PATH]/node_modules/webpack-cli/bin/cli.js:441:16)
    at yargs.parse (/[MY/PATH]/node_modules/webpack-cli/bin/cli.js:528:3)
    at Object.parse (/[MY/PATH]/node_modules/yargs/yargs.js:552:18)
    at /[MY/PATH]/node_modules/webpack-cli/bin/cli.js:219:8
    at Object.<anonymous> (/[MY/PATH]/node_modules/webpack-cli/bin/cli.js:530:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/[MY/PATH]/node_modules/webpack/bin/webpack.js:165:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by romrz** [comment]
I'm having the same issue. Did you find a workaround for this?

**Comment by gparonitti** [comment]
@romrz no, I worked _away_ this issue 😬  and I don't know if they are going to solve or look into the issue.  Apparently no, it's here since July.

**Comment by Zertz** [comment]
@hxlniada Since webpack 5 removes this deprecated API, would you accept a PR to fix this issue?
